* Title page
  The aim of the work is to develop efficient numerical method for
  integrating Markov chain Ion channel models.
  
* Ion channel models
  <1>

  Traditional description of ion channel is known as a gate model.
  This paradigm is modelled by a number of independent gates able to
  open to allow the flow of the ions.

  <2>

  Gate model can be generalized by open and closed states within
  Markov chain model. The transitions between those states are
  determined by transition rates matrix, which normally depends on
  membrane voltage or other variables such as ionic concentrations.


* Integration Methods
** Gate models
   <1>

   The differential equations for both gate and Markov chain model can
   be solved using numerical integration methods for example the
   simplest forward Euler.

   This method finds the approximate solution at the next time step
   using the current solution and the derivative obtained from the
   definition of the gate model.

   The same procedure is then repeated until we get the solution for
   the desired time interval.

   So using larger time step will require less repetitions of the
   procedure. But...

   <2>

   ...if we increase the time step too much, the solution become
   unstable.

   I will show you instability in one of the later slides. For know
   it's enough to know, that the instability makes the solution
   unusable.

   <3>

   A method proposed by Rush and Larsen is based on assumption that
   the independent variable -- here voltage, does not change much
   during one time step and can be "frozen" to the value at the
   beginning of the time step. Then the differential equation is
   solved analytically leads to time-stepping routine shown here.

   <4>

   This method improves accuracy and address instability issues, but
   cannot be directly used for the Markov chain models.
   
** Markov Chain Models
   <1>

   Instead we using the assumptions that the independent variables can
   be "frozen" at the beginning of the time step, and get the
   following time stepping scheme for a matrix.

   The problem here is the computation of exponential of a matrix,
   which is a time consuming task.

   <2>
   
   For that reason, we use the definition of the matrix exponential in
   terms of power series.

   <3>
   
   where the matrix M can be expanded by eigenvalue decomposition.
   Matrix P contains eigenvectors placed in the columns and the matrix
   Lambda contains eigenvalues placed on the corresponding entries of
   the diagonal.

   <4>

   By a identical transformations, we get a formula which contains a
   familiar definition of exponential,

   <5>

   that in fact contains an exponential of a diagonal matrix, that is
   easily computed by simple exponentiation of the entries on the
   diagonal.
   
** Tabulation
   <1>
   
   Avoid expensive eigenvalues and eigenvectors computations at each time
   step we use a lookup table:
   
   <2>
   
   First we save the eigenvalues and eigenvectors matrices for a fine
   grid of membrane voltage.

   <3>
   
   Before the integration starts we compute operator matrix $T$ for
   the specific time step by using saved eigenvalues and eigenvectors.

   <4>
   
   During the simulation we refer to the entry of the operator matrix
   $T$, that corresponds to the the nearest grid voltage value to the
   current voltage.

* Cardiac Cell Model
   
** RyR channel
   <1>

   In the Faber et al. cellular model, that we have been working with, the
   first channel which becomes unstable in forward Euler method is the
   RyR channel.

   It happens at relatively small time steps.

   <2>

   By instability we mean a numerical artefact which can be observed
   on this figure.

   When the time step increases above a certain threshold the
   numerical solution begins to oscillate around the exact
   solution. Those oscillations might happen only for a short time
   interval, but as we increase the time step further, the error goes
   bigger.

   The instability occurs due to the fast transition rates.

   <3>

   In the case of the RyR channel, we have four types of transition
   rates. This figure shows the fastest one of each type and the
   remaining transition rates of each type are just scaled smaller.
   The transition rates matrix is a function of two calcium
   concentrations.
   
   <4>

   The transition rates $alpha$s and $beta$s, are fast and dependent
   on calcium concentrations in the intracellular sub-space.

   As those transition rates are identical in both top and bottom
   parts of the diagram. We separate them into a transition rates
   matrix B.

   <5>

   The remaining transition rates $gamma$s and $delta$s are slow, which
   suggest, that they are resistent to instabilities.

   <6>

   This division allows us to split the solution into two sub-steps.

   The first intermediate calculations gives the contribution of only
   horizontal transitions, for both top and bottom row on the diagram.

   <7>

   The second sub-step uses the intermediate calculation to find the
   contribution of the whole transition rates all together.
   
   This can be effectively done using forward Euler as this sub-system
   is stable even at large time step.

** ICaL channel
   The second Markov chain in the cellular model is the ICaL
   channel. This channel becomes unstable at about 37 us.
   
   <2>

   The model contains two identical layers with voltage dependent
   transition rates.

   The only conductive state is the state $O$ in Mode V.

   <3>

   The switching between the two modes is controlled by transition
   rates $delta$ and $theta$.

   <4>

   Because the switching between modes is independent on the
   particular state, the model can be simplified to a single layer of
   Markov chain, 

   <5>

   and a gate model.

   <6>

   The exponential integrators are used for both parts and the
   fraction of open channels is computed as the product of both parts.
   
* Results and conclusions
  <1>
  
  The figure shows the simulations using the whole cellular model and
  suggested exponential solvers for RyR and ICaL.

  The left panel shows action potential. The reference solution at 1
  us in black.  On the right axis we see the error in logarithmic
  scale defined as deviation from that solution at the time steps 6 us
  in red, 35 us in green and 180 us in blue.

  Here it is apparent, that the solution converges with decreasing
  time step.

  The following two panels show ICaL and RyR current, where all three
  four lines represent the solution.

  <2>

  Exponential integrators allowed the time step increase from about 6
  us to 180 us, which leads to 27-fold reduction of the time required
  for computation.

  <3>

  The time step is still limited by accuracy requirements of the
  particular study.

  And also by instability due to other components.

  <4>

  As a future work we would like develop higher order schemes.
